" Syntax
syntax enable
set t_Co=256
set background=dark
colorscheme molokai
set nonu

" Encoding
set encoding=utf8

" No backup, it's just useless for me
set nobackup
set nowb
set noswapfile

" Tabs
set expandtab
set tabstop=2
set shiftwidth=2
set smarttab

" Enable filetype plugin
filetype plugin on
filetype indent on

set paste
set ignorecase "Ignore case when searching
set smartcase

set hlsearch "Highlight search things

set showmatch "Show matching bracets when text indicator is over them
set mat=2 "How many tenths of a second to blink

" No sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Use modern ctags
let Tlist_Ctags_Cmd='/usr/local/bin/ctags'

""""""""""""""""""""""""""
" Commands mapping
""""""""""""""""""""""""""
nmap <silent> <C-D> :NERDTreeToggle<CR>
map <C-L> :TlistToggle<CR>


" Don't show pyc files in nerdtree
let NERDTreeIgnore = ['\.pyc$']

" Buffers - explore/next/previous: Alt-F12, F12, Shift-F12.
nnoremap <silent> <M-F12> :BufExplorer<CR>
nnoremap <silent> <F12> :bn<CR>
nnoremap <silent> <S-F12> :bp<CR>
