" Setup Vundle
filetype off
set nocompatible

" allow switching between buffers without saving
set hidden

" Remap leader key to ,
let mapleader = ","

if has('win32')
  set rtp+=$HOME/dotfiles/vim/bundle/vundle/
else
  set rtp+=~/.vim/bundle/vundle/
endif
call vundle#rc()

" Enable filetype plugin
filetype plugin on
filetype indent on

" Remove trailing whitespaces
" for code files
autocmd FileType c,cpp,php,python,css,html,javascript autocmd BufWritePre <buffer> :%s/\s\+$//e

" let Vundle manage Vundle
Bundle 'gmarik/vundle'

" My bundles
Bundle 'scrooloose/nerdtree'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'ctrlp.vim'
Bundle 'bufexplorer.zip'
Bundle 'molokai'
Bundle 'bling/vim-airline'
Bundle 'minibufexpl.vim'
Bundle 'docunext/closetag.vim'
Bundle 'EasyGrep'
Bundle 'vimwiki/vimwiki'
Bundle 'tpope/vim-fugitive'

" Enable airline
set laststatus=2

" Syntax
syntax enable
set t_Co=256
set background=dark
colorscheme molokai
set nonu

" Line numbers
set number

" Gui font
set gfn=Consolas:h12:cANSI
set guifont=Consolas:h12:cANSI

" Encoding
set encoding=utf8

" No backup, it's just useless for me
set nobackup
set nowb
set noswapfile

" Tabs
set expandtab
set tabstop=2
set shiftwidth=2
set smarttab

set paste
set ignorecase "Ignore case when searching
set smartcase "Search case insensitive when typing in lowercase
set incsearch " Jump to the next search result while still typing
set scrolloff=4 " Force-scroll 4 lines before/after the cursor
set laststatus=2 " Always show statusline

set hlsearch "Highlight search things

set showmatch "Show matching bracets when text indicator is over them
set mat=2 "How many tenths of a second to blink
set splitright " Open new splits on the right
set splitbelow " Open new splits on the botto
set relativenumber      " Relative line numbering

" Buffers
nmap <C-e> :e#<CR> "Quick buffer shift
"nmap <C-Tab> :bnext<cr> "Switch to next buffer
"nmap <C-S-Tab> :bprevious<cr> "Switch to previous buffer

" No sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

"Split

" Don't use some files: pyc, zip, db, so
set wildignore+=*.pyc,*.so,*.db,*.zip,.DS_Store

" Use modern ctags
let Tlist_Ctags_Cmd='/usr/local/bin/ctags'

" CtrlP configuration
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra' " start directory

""""""""""""""""""""""""""
" Commands mapping
""""""""""""""""""""""""""
nmap <silent> <C-D> :NERDTreeToggle<CR>

" Will allow you to use :w!! to write to a file using sudo if you forgot to sudo
" vim file (it will prompt for sudo password when writing)
cmap w!! %!sudo tee > /dev/null %

" Don't show pyc files in nerdtree
let NERDTreeIgnore = ['\.pyc$']

" Buffers - explore/next/previous: Alt-F12, F12, Shift-F12.
nnoremap <silent> <M-F12> :BufExplorer<CR>
nnoremap <silent> <F12> :bn<CR>
nnoremap <silent> <S-F12> :bp<CR>

" Closetag
autocmd FileType html let b:closetag_html_style=1
autocmd FileType html,xhtml,xml source ~/.vim/bundle/closetag.vim/plugin/closetag.vim
autocmd FileType html,xhtml,xml nmap <C-Tab> <C-_>

" Path auto completion
set wildmode=list:longest,list:full
set wildmenu
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/,CVS*,*.pyc

